### ISSUE TITLE
app.js crash retrieving callsign from IP services data

### ISSUE THREAD

**Issue by captainwasabi** [captainwasabi/topologrjs#22]
root@w6bi-house-pc:~/projects/topologrjs# node app.js
2022-04-18T23:29:52.497Z info:  server:: Started application on port 3001
2022-04-18T23:29:57.305Z http:  server::/info 10.95.109.100 /
/root/projects/topologrjs/app.js:157
    let callsign = nn.substr(0, nn.search("-"));
                      ^

TypeError: Cannot read properties of undefined (reading 'substr')
    at processServices (/root/projects/topologrjs/app.js:157:23)
    at main (/root/projects/topologrjs/app.js:175:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

What did I miss?  This is on Kubuntu 21.10.  Is that too current?

Thanks.

**Comment by Orv** [comment]
Here's the debug file, Doug
file
[debug.zip](https://github.com/captainwasabi/topologrjs/files/8509017/debug.zip)

**Comment by captainwasabi** [comment]
New app.js here https://gist.github.com/captainwasabi/32a72953c75186b6651624519425bdab/archive/22d5aac4621163c156f3d991eddbc373bbf52dde.zip

Just replace the file, then run it.  Don't need to do the /debug/debug link unless it doesn't work again.  I wasn't using the routine that I had already written to handle this exact case (an IP address that doesn't map to a hostname, now it should use the ip address for the name..

**Comment by Orv** [comment]
I'll check this either tonight or tomorrow and let you know.

Orv

**Comment by Orv** [comment]
Got it loaded and it started fine.  I started expanding stuff but after a couple of minutes the display froze, then the display cleared (went blank).  I confirmed the web server is still running.  Got this out of node:
------------------------------------
2022-04-19T02:28:32.635Z info:  server:: Started application on port 3001
2022-04-19T02:28:57.959Z http:  server::/info 10.95.109.100 /
2022-04-19T02:33:48.662Z http:  server::/info 10.95.109.100 /info/KE6BXT-OCRACES-LomaRidge
2022-04-19T02:33:48.799Z http:  10.95.109.100 /log
2022-04-19T02:33:48.799Z error:         10.95.109.100 0: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"
2022-04-19T02:33:48.931Z http:  10.95.109.100 /log
2022-04-19T02:33:48.931Z error:         10.95.109.100 1: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"
2022-04-19T02:33:49.044Z http:  10.95.109.100 /log
2022-04-19T02:33:49.045Z error:         10.95.109.100 2: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"
2022-04-19T02:33:49.173Z http:  10.95.109.100 /log
2022-04-19T02:33:49.173Z error:         10.95.109.100 3: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"
-------------------------------
Could it have to do with the fact that it's trying to keep track of ~600 nodes?  :-)

**Comment by captainwasabi** [comment]
Yeah, that Error: ResizeObserver it supposed to be ignorable, but it really means there are performance issues.  I think this is down in the internals of vis-network, but I'm not sure.  I'll have a new release with an exportNet and importNet buttons that should help me see what is going on.

Thanks again, I would never be able to test against a large network like this.

**Comment by Orv** [comment]
It continues to freeze periodically with more of those messages:

2022-04-19T02:43:49.558Z error:         10.95.109.100 17: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"
2022-04-19T02:43:49.639Z http:  10.95.109.100 /log
2022-04-19T02:43:49.639Z error:         10.95.109.100 18: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"
2022-04-19T02:43:49.707Z http:  10.95.109.100 /log
2022-04-19T02:43:49.707Z error:         10.95.109.100 19: "Error: ResizeObserver loop completed with undelivered notifications.\nScript: \nLine: 0\nColumn: 0\nStackTrace: null"

**Comment by Orv** [comment]
You're very welcome!  I enjoy testing stuff like this.

**Comment by Orv** [comment]
Here's different error.  Might be OK, though...

2022-04-19T03:14:05.989Z warn:  server::load: http://KN6KSF-COAST-RM5.local.mesh/cgi-bin/sysinfo.json?services_local=1&link_info=1 fetch failed:
 FetchError: request to http://kn6ksf-coast-rm5.local.mesh/cgi-bin/sysinfo.json?services_local=1&link_info=1 failed, reason: connect EHOSTUNREACH 10.160.200.44:80
    at ClientRequest.<anonymous> (file:///root/projects/topologrjs/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-04-19T03:14:05.989Z warn:  server::getNodeData KN6KSF-COAST-RM5.local.mesh info request failed:
 TypeError: Cannot read properties of null (reading 'json')
    at getNodeData (/root/projects/topologrjs/app.js:229:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /root/projects/topologrjs/app.js:60:11

**Comment by captainwasabi** [comment]
Yeah, that didn't crash right?  It either means the node has gone offline since the last time the net was refreshed (so even though it shows a link it's really not there right now) or that node is running an old version of the AREDN firmware from before the json API was implemented.

**Comment by Orv** [comment]
The app didn't crash.  KN6KSF-COAST-RM5.local.mesh is running version 3.21.4.0.  It's not local, but rather 20 hops away, about 85 miles as the crow flies.  Its OLSR appears to be still running.

**Comment by captainwasabi** [comment]
I have a timeout of 3 seconds for fetching api data.  At 20 hops that may be a tad short.  if you are good with editing line 211 in the app.js file change 3000 to 10000.  It's in milliseconds so that'll give a 10 second timeout.  If you use a web browser to go to http://kn6ksf-coast-rm5.local.mesh/cgi-bin/sysinfo.json?services_local=1&link_info=1 you should be able to estimate the delay before the json comes up.

**Comment by Orv** [comment]
Can't retrieve sysinfo.json on that system;  I suspect it doesn't exist.  Nor can I bring up the status page now;  I think it's a bit ill.

**Comment by captainwasabi** [comment]
I just pushed b5.  If you have positions and colors you want to save then save your settings first.  Then delete your current install, and repeat the installation instructions.  Once it's loaded up, click the Export Net button.  Then attach the exported file(s) to a comment here. 

Thanks,

**Comment by Orv** [comment]
Followed the reinstall instructions, but got this:

root@w6bi-house-pc:~/projects/topologrjs-main# node app.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /root/projects/topologrjs-main/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/projects/topologrjs-main/app.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/projects/topologrjs-main/app.js' ]
}

Node.js v17.9.0

**Comment by captainwasabi** [comment]
Did the `npm install` command complete successfully?

**Comment by Orv** [comment]
Oh - didnt' realize that step was required.  Yes, it fixed it.  More testing in the morning.

**Comment by captainwasabi** [comment]
I think what I am going to try for untangling is to have a "Grid" (or maybe "UnTangle") button that sorts all the nodes by nodename then places them into a regular grid.  Should at least get things spread out more to start with.

**Comment by captainwasabi** [comment]
Grid is in, I don't like it, plus several other functions to help pull apart a tangle.  Having decent auto-generated layouts is important. (but I didn't realize when I started that so many nets are so large.

If there are any embedded issues that I have not addressed please move them to a new issue

**Comment by captainwasabi** [comment]
Try the latest release and let me know.  Watch the video [here](https://github.com/captainwasabi/topologrjs)
